### PR TITLE
Gnome 45 + Adwaita + misc.

### LINKED ISSUE #44: prepare to Gnome 45/ESM
So Gnome 45 will move to ESM, that means all extensions will be broken when the new Shell version arrive. There are some guides on how to port extensions to ESM, eg.: https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm and https://www.youtube.com/watch?v=OBnMl8Jk_Rg. 

There's also a [matrix channel](https://matrix.to/#/#extensions:gnome.org) with an active community willing to help other extension developers with this transition.

### PR DESCRIPTION
**Pull request by gtsiam**
Quoting [you](https://github.com/p91paul/middleclickclose/issues/44#issuecomment-1681397032) from #44:
> ... otherwise I hope some nice guy will step in with a pull request.

So here goes. Though I did a bit more for extra credit. I'd never worked on a gnome extension before so I thought I might as well:
- Port the settings to Gtk4 + Adwaita.
- Include a Makefile, so now you can just `make` / `make install` and be done with it.
  - Also `make pot` / `make po` to generate the po template and update the po files respectively. Make sure to do the latter occasionally from now on.
  - Moved the source directory to `src` because I refuse to type `middleclickclose@paolo.tranquilli.gmail.com` more than once.
- Add a Greek translation because why not.

I _could_ split this into multiple commits, but frankly I can't be bothered to do it since this is almost a rewrite at this point.

Closes #44

### CODE REVIEW

File: buildforupload.sh
Comment (p91paul) [inline buildforupload.sh:1]: Please keep this file. Maybe its content can be replaced by make pack?
I do not know pack tool, but the zip file must contain compiled schemas and not contain po files, otherwise extensions.gnome.org will reject it. Does the pack command fulfill these requirements?

File: .gitignore [hunk 1]
```diff
@@ -1,2 +1,2 @@
-middleclickclose@paolo.tranquilli.gmail.com.zip
-gschemas.compiled
```
Comment (p91paul) [inline .gitignore:2]: I think it's alright for the pot file to be committed, whereas gschemas.compiled still needs to be ignored (for development purposes it's easier to run the extension directly from the git repo)

File: Makefile
Comment (p91paul) [inline Makefile:1]: I don't see a step to compile po to mo files, does pack perform this as well? mo files must be in the zip file uploaded to extensions.gnome.org

**Review by p91paul — CHANGES_REQUESTED** [review]
Thanks for your pull request. I added some comments, some of them are just doubts or stuff for my convenience, just one of them is a blocker.
This pull request will be likely merged when gnome 45 hits arch linux and I can test it.
If you are interested, this extension might need a longer-term mantainer. I would be happy to give you commit rights and ownership on extensions.gnome.org.

File: src/extension.js [hunk 2]
```diff
@@ -0,0 +1,133 @@
...
+	#close_button;
+	#rearrange_delay;
+
+	enable() {
+		this.enabled = true;
+		this.ensurePatched();
+	}
+
+	disable() {
+		this.enabled = false;
```
[the remark this answers is not in the document]
Comment (gtsiam) [reply src/extension.js:40]: It does _effectively_ undo everything enable did. The reason I'd rather keep this is the classic ABA problem:

- Quick close in overview is enabled and overrides `_addWindowClone()`
- Another extension also overrides `_addWindowClone()`
- Quick close in overview is disabled, and restores the original (from gnome-shell) `_addWindowClone()`
- Oops, we partly disabled another extension (!)

There's more ways the original approach can go wrong too, but I'll ask around on the matrix channel and get back to you on this.

File: buildforupload.sh
Comment (gtsiam) [reply buildforupload.sh:1]: Yes, `make pack` is intended to replace it this file. I got it from [here](https://gjs.guide/extensions/development/translations.html#compiling-translations).

Looking at the zip, it does indeed compile the schemas and only add mo files:

```
ouch list middleclickclose@paolo.tranquilli.gmail.com.shell-extension.zip 
Archive: /home/gtsiam/Dev/git/middleclickclose/middleclickclose@paolo.tranquilli.gmail.com.shell-extension.zip
metadata.json
locale/
locale/de/
locale/de/LC_MESSAGES/
locale/de/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
locale/el/
locale/el/LC_MESSAGES/
locale/el/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
locale/fr/
locale/fr/LC_MESSAGES/
locale/fr/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
locale/it/
locale/it/LC_MESSAGES/
locale/it/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
locale/nl/
locale/nl/LC_MESSAGES/
locale/nl/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
locale/sk/
locale/sk/LC_MESSAGES/
locale/sk/LC_MESSAGES/org.gnome.shell.extensions.middleclickclose.mo
schemas/
schemas/org.gnome.shell.extensions.middleclickclose.gschema.xml
schemas/gschemas.compiled
prefs.js
extension.js
```

File: Makefile
Comment (gtsiam) [reply Makefile:1]: yes it does, see my earlier comment.

File: .gitignore (hunk 1 above)
Comment (gtsiam) [reply .gitignore:2]: The way I did development was to just run `make install` after every change and then restart gnome-shell and it worked great (except the fact that I had to run a nested session because gnome 45 beta-1 seems to crash on restart for some reason, but anyway).

I didn't commit the pot file, because I couldn't find a way to make `make pot` idempotent (the creation timestamp would update every time). Maybe it's worth keeping a copy of the pot file `make po` was run with somehow? But I'm not sure how I would do that while keeping `make pot` idempotent.

**Comment by gtsiam** [comment]
Alright, I left you some answers, resolve those you think are resolved and we go from there. I'll post back once I get an answer from matrix about the enable/disable approach.

Though for testing, I'm also on Arch. You can actually test gnome 45 beta right now using the [fcgu](https://codeberg.org/fabiscafe/fcgu#installation) repository. I've been daily driving it, and it's been reasonably stable (not that I'd recommend daily driving it if you're not comfortable with the occasional so-bump induced crash).

File: src/extension.js (hunk 2 above)
[the remark this answers is not in the document]
Comment (gtsiam) [reply src/extension.js:40]: So you're right on this. Apparently gnome-shell [reapplies](https://discourse.gnome.org/t/extension-disable-called-on-session-mode-change-but-only-for-the-first-time/15832) other extensions on disable(). I'll be back with a fix for this.

File: buildforupload.sh
Comment (gtsiam) [reply buildforupload.sh:1]: I'll assume this is fine to leave as-is

**Comment by gtsiam** [comment]
@p91paul Okay, that should be all on my end.

> If you are interested, this extension might need a longer-term mantainer. I would be happy to give you commit rights and ownership on extensions.gnome.org.

I've been patching this extension early for my own use for a while now, just didn't bother making a pr for a simple version addition to `metadata.json`. So yeah, I'd be happy to help - I've been using this extension for a very long time already.

**Comment by zumoshi** [comment]
Hi,
Thanks for the work to make it compatible with Gnome 45
but the [extensions](https://extensions.gnome.org/extension/352/middle-click-to-close-in-overview/) page still lists it as incompatible.
@p91paul Is there any plans to update it there or should I install from git instead?

**Comment by p91paul** [comment]
@gtsiam is becoming the new maintainer and we are having a bit of trouble transferring ownership of the extension. I just uploaded a new version from master, so hopefully it'll be online in a few days anyway.
